require_relative "six_nations/version"
require_relative "six_nations/cli"
require_relative "six_nations/team"
require_relative "six_nations/tournament"
require_relative "six_nations/player"
require_relative "six_nations/fixture"

require "pry"
require "nokogiri"
require "open-uri"
require "terminal-table"
